const entry = (value) => Object.freeze(value);

export const TOOL_CATALOG = Object.freeze([
  entry({ id: "codex", name: "OpenAI Codex", aliases: ["codex"], executables: ["codex.exe", "codex"], processNames: ["Codex.exe", "codex.exe"], locations: ["{home}/.codex", "{localAppData}/Codex", "{roamingAppData}/Codex"], markers: ["config.toml", "sessions", "skills"], transports: ["cli", "mcp-client", "manual-packet"] }),
  entry({ id: "chatgpt", name: "ChatGPT", aliases: ["chatgpt", "openai"], executables: ["ChatGPT.exe"], processNames: ["ChatGPT.exe"], locations: ["{localAppData}/ChatGPT", "{roamingAppData}/ChatGPT", "{localAppData}/Packages/OpenAI.ChatGPT-Desktop_*"], markers: ["LocalCache", "LocalState"], transports: ["desktop", "mcp-client", "manual-packet"] }),
  entry({ id: "claude", name: "Claude and Claude Code", aliases: ["claude", "anthropic"], executables: ["claude.exe", "claude"], processNames: ["Claude.exe", "claude.exe"], locations: ["{home}/.claude", "{localAppData}/Claude", "{roamingAppData}/Claude"], markers: ["claude_desktop_config.json", "projects", "history.jsonl"], transports: ["cli", "mcp-client", "manual-packet"] }),
  entry({ id: "gemini", name: "Google Gemini", aliases: ["gemini", "google"], executables: ["gemini.exe", "gemini"], processNames: ["Gemini.exe", "gemini.exe"], locations: ["{home}/.gemini", "{localAppData}/Gemini", "{roamingAppData}/Gemini"], markers: ["settings.json", "tmp"], transports: ["cli", "mcp-client", "manual-packet"] }),
  entry({ id: "kimi", name: "Kimi", aliases: ["kimi", "moonshot"], executables: ["Kimi.exe", "kimi.exe", "kimi"], processNames: ["Kimi.exe", "kimi.exe"], locations: ["{localAppData}/Kimi", "{roamingAppData}/Kimi", "{localAppData}/Moonshot", "{roamingAppData}/Moonshot"], markers: ["User Data", "Local Storage"], transports: ["api", "openai-compatible", "manual-packet"] }),
  entry({ id: "perplexity", name: "Perplexity", aliases: ["perplexity", "pplx"], executables: ["Perplexity.exe", "perplexity.exe"], processNames: ["Perplexity.exe", "perplexity.exe"], locations: ["{localAppData}/Perplexity", "{roamingAppData}/Perplexity", "{localAppData}/Packages/PerplexityAI.Perplexity_*"], markers: ["User Data", "LocalCache", "LocalState"], transports: ["api", "desktop", "manual-packet"] }),
  entry({ id: "manus", name: "Manus", aliases: ["manus"], executables: ["Manus.exe", "manus.exe"], processNames: ["Manus.exe", "manus.exe"], locations: ["{localAppData}/Manus", "{roamingAppData}/Manus"], markers: ["User Data", "Local Storage"], transports: ["browser", "manual-packet"] }),
  entry({ id: "grok", name: "xAI Grok", aliases: ["grok", "xai"], executables: ["Grok.exe", "grok.exe"], processNames: ["Grok.exe", "grok.exe"], locations: ["{localAppData}/Grok", "{roamingAppData}/Grok", "{localAppData}/xAI"], markers: ["User Data", "Local Storage"], transports: ["api", "manual-packet"] }),
  entry({ id: "github-copilot", name: "GitHub Copilot", aliases: ["github copilot", "copilot"], executables: ["github-copilot-cli.exe", "github-copilot-cli"], processNames: [], locations: ["{home}/.config/github-copilot", "{roamingAppData}/Code/User/globalStorage/github.copilot-chat"], markers: ["config.json", "state.vscdb"], transports: ["editor", "mcp-client", "manual-packet"] }),
  entry({ id: "cursor", name: "Cursor", aliases: ["cursor"], executables: ["Cursor.exe", "cursor.exe", "cursor"], processNames: ["Cursor.exe"], locations: ["{home}/.cursor", "{localAppData}/Programs/cursor", "{roamingAppData}/Cursor"], markers: ["mcp.json", "User", "workspaceStorage"], transports: ["editor", "mcp-client", "manual-packet"] }),
  entry({ id: "windsurf", name: "Windsurf", aliases: ["windsurf", "codeium"], executables: ["Windsurf.exe", "windsurf.exe", "windsurf"], processNames: ["Windsurf.exe"], locations: ["{home}/.codeium/windsurf", "{localAppData}/Programs/Windsurf", "{roamingAppData}/Windsurf"], markers: ["mcp_config.json", "User", "workspaceStorage"], transports: ["editor", "mcp-client", "manual-packet"] }),
  entry({ id: "vscode", name: "Visual Studio Code", aliases: ["visual studio code", "vscode", "code"], executables: ["Code.exe", "code.cmd", "code"], processNames: ["Code.exe"], locations: ["{home}/.vscode", "{localAppData}/Programs/Microsoft VS Code", "{roamingAppData}/Code"], markers: ["mcp.json", "settings.json", "workspaceStorage", "globalStorage"], transports: ["editor", "mcp-client"] }),
  entry({ id: "cline", name: "Cline", aliases: ["cline"], executables: [], processNames: [], locations: ["{roamingAppData}/Code/User/globalStorage/saoudrizwan.claude-dev", "{home}/.cline"], markers: ["settings", "tasks"], transports: ["editor", "mcp-client", "manual-packet"] }),
  entry({ id: "continue", name: "Continue", aliases: ["continue"], executables: ["continue.exe", "continue"], processNames: [], locations: ["{home}/.continue", "{roamingAppData}/Code/User/globalStorage/continue.continue"], markers: ["config.json", "config.yaml", "sessions"], transports: ["editor", "mcp-client", "manual-packet"] }),
  entry({ id: "aider", name: "Aider", aliases: ["aider"], executables: ["aider.exe", "aider"], processNames: ["aider.exe"], locations: ["{home}/.aider", "{home}/.config/aider"], markers: [".aider.conf.yml", ".aider.chat.history.md"], transports: ["cli", "manual-packet"] }),
  entry({ id: "opencode", name: "OpenCode", aliases: ["opencode"], executables: ["opencode.exe", "opencode"], processNames: ["opencode.exe"], locations: ["{home}/.config/opencode", "{localAppData}/opencode", "{roamingAppData}/opencode"], markers: ["config.json", "opencode.json"], transports: ["cli", "mcp-client", "manual-packet"] }),
  entry({ id: "ollama", name: "Ollama", aliases: ["ollama"], executables: ["ollama.exe", "ollama"], processNames: ["ollama.exe", "ollama app.exe"], locations: ["{home}/.ollama", "{localAppData}/Programs/Ollama"], markers: ["models", "id_ed25519.pub"], transports: ["local-api", "openai-compatible"] }),
  entry({ id: "lm-studio", name: "LM Studio", aliases: ["lm studio", "lmstudio"], executables: ["LM Studio.exe", "lms.exe", "lms"], processNames: ["LM Studio.exe"], locations: ["{home}/.lmstudio", "{localAppData}/LM Studio", "{roamingAppData}/LM Studio"], markers: ["models", "settings"], transports: ["local-api", "openai-compatible"] }),
  entry({ id: "amazon-q", name: "Amazon Q", aliases: ["amazon q", "amazonq"], executables: ["q.exe", "q"], processNames: ["Amazon Q.exe"], locations: ["{home}/.aws/amazonq", "{localAppData}/Amazon Q", "{roamingAppData}/Amazon Q"], markers: ["settings.json"], transports: ["cli", "editor", "manual-packet"] })
]);

export function getTool(toolId) {
  return TOOL_CATALOG.find(({ id }) => id === toolId) ?? null;
}
